version: "3.8"

networks:
  default:
    external:
      name: backend
services:
  mymoviedb:
    image: mongo:latest
    container_name: mongodb_one
    ports:
      - 27017:27017
  persistence:
    image: persistence
    container_name: persistence
    ports:
      - 8080:8080
    links:
      - mypersistence